[project]
name = "psyche"
version = "0.1.0"
description = "AI Agent Society Simulation"
authors = [{name = "ExpressGradient", email = "johndoeknown@protonmail.com"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
